### PR TITLE
Sample-confirmation-modal_CU-kqcrfm

### PR DESCRIPTION
**Pull request by a-wilkes**

### CODE REVIEW

**Comment by a-wilkes** [comment]
Task linked: [CU-kqcrfm Sample confirmation modal](https://app.clickup.com/t/kqcrfm)

**Comment by lpboucher** [comment]
Task linked: [CU-kqcrfm Sample confirmation modal](https://app.clickup.com/t/kqcrfm)

**Comment by a-wilkes** [comment]
I made the assumption that the modal connected to the floating action button should always be around, but hidden, showing itself when the floating action button is clicked. Let me know if this isn't the right way to do it.

**Review by lpboucher — APPROVED** [review]

**Comment by lpboucher** [comment]
Nicely done!

**Pull request merged**
