### PR TITLE
Cart-click_CU-md8h9t

### PR DESCRIPTION
**Pull request by a-wilkes**

### CODE REVIEW

**Comment by a-wilkes** [comment]
Task linked: [CU-md8h9t Cart click](https://app.clickup.com/t/md8h9t)

**Comment by lpboucher** [comment]
Task linked: [CU-md8h9t Cart click](https://app.clickup.com/t/md8h9t)

**Comment by a-wilkes** [comment]
The ticket asked to put the click callback in the sidebar, but the blocking ticket [Cart-click](https://app.clickup.com/t/md8hfd) asked to have the generic widget emit click events. Since the generic widget click event logic was already around, I chose to use that instead. Let me know if you want the logic moved to the sidebar.

**Review by lpboucher — CHANGES_REQUESTED** [review]
This is approved, will merge after the refactor ticket is fully merged

**Pull request merged**
